[build-system]
requires = ["setuptools", "wheel", "cffi>=0.8", "patch-ng"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-verbosity = 1
test-requires = "pytest"
test-command = "pytest {project}/tests"

# Before building, install patch-ng, which is needed for applying patches.
before-build = "pip install patch-ng"

# Build CPython wheels
[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
before-build = "pip install patch-ng"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
before-build = "pip install patch-ng"

[tool.cibuildwheel.windows]
archs = ["AMD64", "ARM64"]
before-build = "pip install patch-ng"
